FROM ubuntu
RUN	apt-get update
RUN apt-get install -y software-properties-common
RUN	apt-get update
RUN add-apt-repository -y ppa:ethereum/ethereum
RUN	apt-get update
RUN apt-get install -y ethereum 
COPY ./ /app
WORKDIR /app/bc_node
RUN ./init.sh
CMD ./start.sh
