export const GETTING_BANK_ACCOUNTS = 'GETTING_BANK_ACCOUNTS';
export const GET_BANK_ACCOUNTS_SUCCESS = 'GET_BANK_ACCOUNTS_SUCCESS';
export const GET_BANK_ACCOUNTS_FAIL = 'GET_BANK_ACCOUNTS_FAIL';

export const GETTING_BANK_ACCOUNT = 'GETTING_BANK_ACCOUNT';
export const GET_BANK_ACCOUNT_SUCCESS = 'GET_BANK_ACCOUNT_SUCCESS';
export const GET_BANK_ACCOUNT_FAIL = 'GET_BANK_ACCOUNT_FAIL';

export const ADDING_BANK_ACCOUNT = 'ADDING_BANK_ACCOUNT';
export const ADDING_BANK_ACCOUNT_SUCCESS = 'ADDING_BANK_ACCOUNT_SUCCESS';
export const ADDING_BANK_ACCOUNT_FAIL = 'ADDING_BANK_ACCOUNT_FAIL';
export const ADDING_BANK_ACCOUNT_CLEAR = 'ADDING_BANK_ACCOUNT_CLEAR';

export const ADDING_BANK_ACCOUNT_BALANCE = "ADDING_BANK_ACCOUNT_BALANCE";
export const ADDING_BANK_ACCOUNT_BALANCE_SUCCESS = "ADDING_BANK_ACCOUNT_BALANCE_SUCCESS";
export const ADDING_BANK_ACCOUNT_BALANCE_FAIL = "ADDING_BANK_ACCOUNT_BALANCE_FAIL";
export const ADDING_BANK_ACCOUNT_BALANCE_CLEAR = "ADDING_BANK_ACCOUNT_BALANCE_CLEAR";