export const GETTING_BLOCKCHAIN_TRANSACTIONS = 'GETTING_BLOCKCHAIN_TRANSACTIONS';
export const GET_BLOCKCHAIN_TRANSACTIONS_SUCCESS = 'GET_BLOCKCHAIN_TRANSACTIONS_SUCCESS';
export const GET_BLOCKCHAIN_TRANSACTIONS_FAIL = 'GET_BLOCKCHAIN_TRANSACTIONS_FAIL';

export const GETTING_BLOCKCHAIN_TRANSACTION = 'GETTING_BLOCKCHAIN_TRANSACTION';
export const GET_BLOCKCHAIN_TRANSACTION_SUCCESS = 'GET_BLOCKCHAIN_TRANSACTION_SUCCESS';
export const GET_BLOCKCHAIN_TRANSACTION_FAIL = 'GET_BLOCKCHAIN_TRANSACTION_FAIL';

