export const GETTING_BLOCKCHAIN_BLOCKS = 'GETTING_BLOCKCHAIN_BLOCKS';
export const GET_BLOCKCHAIN_BLOCKS_SUCCESS = 'GET_BLOCKCHAIN_BLOCKS_SUCCESS';
export const GET_BLOCKCHAIN_BLOCKS_FAIL = 'GET_BLOCKCHAIN_BLOCKS_FAIL';

export const GETTING_BLOCKCHAIN_BLOCK = 'GETTING_BLOCKCHAIN_BLOCK';
export const GET_BLOCKCHAIN_BLOCK_SUCCESS = 'GET_BLOCKCHAIN_BLOCK_SUCCESS';
export const GET_BLOCKCHAIN_BLOCK_FAIL = 'GET_BLOCKCHAIN_BLOCK_FAIL';

