export const GETTING_INTEREST_RATES = 'GETTING_INTEREST_RATES';
export const GET_INTEREST_RATES_SUCCESS = 'GET_INTEREST_RATES_SUCCESS';
export const GET_INTEREST_RATES_FAIL = 'GET_INTEREST_RATES_FAIL';