export const GETTING_INTEREST_RATES = 'GETTING_INTEREST_RATES';
export const GET_INTEREST_RATES_SUCCESS = 'GET_INTEREST_RATES_SUCCESS';
export const GET_INTEREST_RATES_FAIL = 'GET_INTEREST_RATES_FAIL';

export const GETTING_INTEREST_RATE = 'GETTING_INTEREST_RATE';
export const GET_INTEREST_RATE_SUCCESS = 'GET_INTEREST_RATE_SUCCESS';
export const GET_INTEREST_RATE_FAIL = 'GET_INTEREST_RATE_FAIL';

export const UPDATING_INTEREST_RATE = 'UPDATING_INTEREST_RATE';
export const UPDATE_INTEREST_RATE_SUCCESS = 'UPDATE_INTEREST_RATE_SUCCESS';
export const UPDATE_INTEREST_RATE_FAIL = 'UPDATE_INTEREST_RATE_FAIL';

export const CLEAR_UPDATE_INTEREST_RATE = 'CLEAR_UPDATE_INTEREST_RATE';
