export const GETTING_SETTINGS = 'GETTING_SETTINGS';
export const GET_SETTINGS_SUCCESS = 'GET_SETTINGS_SUCCESS';
export const GET_SETTINGS_FAIL = 'GET_SETTINGS_FAIL';

export const UPDATING_SETTING = 'UPDATING_SETTING';
export const UPDATE_SETTING_SUCCESS = 'UPDATE_SETTING_SUCCESS';
export const UPDATE_SETTING_FAIL = 'UPDATE_SETTING_FAIL';
export const UPDATE_SETTING_CLEAR = 'UPDATE_SETTING_CLEAR';

export const GETTING_SETTING = 'GETTING_SETTING';
export const GET_SETTING_SUCCESS = 'GET_SETTING_SUCCESS';
export const GET_SETTING_FAIL = 'GET_SETTING_FAIL';