version: "3.8"
services:
    #PHP Service
    bc-php:
        build:
            context: .
            dockerfile: Dockerfile
        image: bc-php-image
        container_name: bc-php
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./deployment/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network
    
    #Nginx Service
    bc-nginx:
        image: nginx:alpine
        container_name: bc-nginx
        restart: unless-stopped
        tty: true
        ports:
            - "5010:80"
            - "444:443"
        volumes:
            - ./:/var/www
            - ./deployment/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    #MySQL Service
    bc-db:
        image: mysql:8
        container_name: bc-db
        restart: unless-stopped
        tty: true
        ports:
            - "5030:3306"
        environment:
            MYSQL_DATABASE: bc_bank_transfer
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./deployment/mysql/db:/var/lib/mysql
            - ./deployment/mysql:/etc/mysql/conf.d    
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge